/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-24-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Integration {

    public static void myIntegration() {    
        
        String salesforce = 'I Love Salesforce';
        System.debug('Here is the Integration class:' + salesforce);
    }
    

}